/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard.invites'
import { Route as DashboardImportsRouteImport } from './routes/dashboard.imports'
import { Route as DashboardGuestsRouteImport } from './routes/dashboard.guests'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardInvitesRunIdRouteImport } from './routes/dashboard.invites.$runId'
import { Route as DashboardEventsEventIdAudienceRouteImport } from './routes/dashboard.events.$eventId.audience'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportsRoute = DashboardImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsRoute = DashboardGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitesRunIdRoute = DashboardInvitesRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => DashboardInvitesRoute,
} as any)
const DashboardEventsEventIdAudienceRoute =
  DashboardEventsEventIdAudienceRouteImport.update({
    id: '/$eventId/audience',
    path: '/$eventId/audience',
    getParentRoute: () => DashboardEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/invites': typeof DashboardInvitesRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/invites/$runId': typeof DashboardInvitesRunIdRoute
  '/dashboard/events/$eventId/audience': typeof DashboardEventsEventIdAudienceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/invites': typeof DashboardInvitesRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/invites/$runId': typeof DashboardInvitesRunIdRoute
  '/dashboard/events/$eventId/audience': typeof DashboardEventsEventIdAudienceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/events': typeof DashboardEventsRouteWithChildren
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/imports': typeof DashboardImportsRoute
  '/dashboard/invites': typeof DashboardInvitesRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRoute
  '/dashboard/invites/$runId': typeof DashboardInvitesRunIdRoute
  '/dashboard/events/$eventId/audience': typeof DashboardEventsEventIdAudienceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/events'
    | '/dashboard/guests'
    | '/dashboard/imports'
    | '/dashboard/invites'
    | '/events/$eventId'
    | '/dashboard/invites/$runId'
    | '/dashboard/events/$eventId/audience'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/events'
    | '/dashboard/guests'
    | '/dashboard/imports'
    | '/dashboard/invites'
    | '/events/$eventId'
    | '/dashboard/invites/$runId'
    | '/dashboard/events/$eventId/audience'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/audit'
    | '/dashboard/events'
    | '/dashboard/guests'
    | '/dashboard/imports'
    | '/dashboard/invites'
    | '/events/$eventId'
    | '/dashboard/invites/$runId'
    | '/dashboard/events/$eventId/audience'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/imports': {
      id: '/dashboard/imports'
      path: '/imports'
      fullPath: '/dashboard/imports'
      preLoaderRoute: typeof DashboardImportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests': {
      id: '/dashboard/guests'
      path: '/guests'
      fullPath: '/dashboard/guests'
      preLoaderRoute: typeof DashboardGuestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invites/$runId': {
      id: '/dashboard/invites/$runId'
      path: '/$runId'
      fullPath: '/dashboard/invites/$runId'
      preLoaderRoute: typeof DashboardInvitesRunIdRouteImport
      parentRoute: typeof DashboardInvitesRoute
    }
    '/dashboard/events/$eventId/audience': {
      id: '/dashboard/events/$eventId/audience'
      path: '/$eventId/audience'
      fullPath: '/dashboard/events/$eventId/audience'
      preLoaderRoute: typeof DashboardEventsEventIdAudienceRouteImport
      parentRoute: typeof DashboardEventsRoute
    }
  }
}

interface DashboardEventsRouteChildren {
  DashboardEventsEventIdAudienceRoute: typeof DashboardEventsEventIdAudienceRoute
}

const DashboardEventsRouteChildren: DashboardEventsRouteChildren = {
  DashboardEventsEventIdAudienceRoute: DashboardEventsEventIdAudienceRoute,
}

const DashboardEventsRouteWithChildren = DashboardEventsRoute._addFileChildren(
  DashboardEventsRouteChildren,
)

interface DashboardInvitesRouteChildren {
  DashboardInvitesRunIdRoute: typeof DashboardInvitesRunIdRoute
}

const DashboardInvitesRouteChildren: DashboardInvitesRouteChildren = {
  DashboardInvitesRunIdRoute: DashboardInvitesRunIdRoute,
}

const DashboardInvitesRouteWithChildren =
  DashboardInvitesRoute._addFileChildren(DashboardInvitesRouteChildren)

interface DashboardRouteChildren {
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardEventsRoute: typeof DashboardEventsRouteWithChildren
  DashboardGuestsRoute: typeof DashboardGuestsRoute
  DashboardImportsRoute: typeof DashboardImportsRoute
  DashboardInvitesRoute: typeof DashboardInvitesRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardEventsRoute: DashboardEventsRouteWithChildren,
  DashboardGuestsRoute: DashboardGuestsRoute,
  DashboardImportsRoute: DashboardImportsRoute,
  DashboardInvitesRoute: DashboardInvitesRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  EventsEventIdRoute: EventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
